// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCfTS6EY8RiZzqSeDqxdLFWkZuyrrEt2Zo',
    appId: '1:1050031108337:web:81427e73dbdb56056ab950',
    messagingSenderId: '1050031108337',
    projectId: 'ratings-d9c72',
    authDomain: 'ratings-d9c72.firebaseapp.com',
    storageBucket: 'ratings-d9c72.firebasestorage.app',
    measurementId: 'G-1JYKPNS280',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBG2RWBDyGUf-ijTINJ839lqb4gsxE7js0',
    appId: '1:1050031108337:android:7d9344d5d960f5336ab950',
    messagingSenderId: '1050031108337',
    projectId: 'ratings-d9c72',
    storageBucket: 'ratings-d9c72.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD9vP9s-E1PfIteXkIpH8TggS_wL49MVeg',
    appId: '1:1050031108337:ios:3fe367d99e1a16246ab950',
    messagingSenderId: '1050031108337',
    projectId: 'ratings-d9c72',
    storageBucket: 'ratings-d9c72.firebasestorage.app',
    iosClientId: '1050031108337-dm1s9qmhk30hso8uo7rnpj1qn780udmq.apps.googleusercontent.com',
    iosBundleId: 'com.example.ratingsapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD9vP9s-E1PfIteXkIpH8TggS_wL49MVeg',
    appId: '1:1050031108337:ios:3fe367d99e1a16246ab950',
    messagingSenderId: '1050031108337',
    projectId: 'ratings-d9c72',
    storageBucket: 'ratings-d9c72.firebasestorage.app',
    iosClientId: '1050031108337-dm1s9qmhk30hso8uo7rnpj1qn780udmq.apps.googleusercontent.com',
    iosBundleId: 'com.example.ratingsapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCfTS6EY8RiZzqSeDqxdLFWkZuyrrEt2Zo',
    appId: '1:1050031108337:web:5a9636b192f146b36ab950',
    messagingSenderId: '1050031108337',
    projectId: 'ratings-d9c72',
    authDomain: 'ratings-d9c72.firebaseapp.com',
    storageBucket: 'ratings-d9c72.firebasestorage.app',
    measurementId: 'G-YVKQV505G2',
  );

}